const blocks = [
  {
    id: '1',
    itemId: 'minecraft:stone',
    name: 'Stone',
    stackable: true,
    size: 64,
    url: 'https://minecraftitemids.com/item/128/stone.png',
  },
  {
    id: '2',
    itemId: 'minecraft:grass_block',
    name: 'Grass Block',
    stackable: true,
    size: 64,
    url: 'https://minecraftitemids.com/item/128/grass_block.png',
  },
  {
    id: '3',
    itemId: 'minecraft:dirt',
    name: 'Dirt',
    stackable: true,
    size: 64,
    url: 'https://minecraftitemids.com/item/128/dirt.png',
  },
  {
    id: '4',
    itemId: 'minecraft:cobblestone',
    name: 'Cobblestone',
    stackable: true,
    size: 64,
    url: 'https://minecraftitemids.com/item/128/cobblestone.png',
  },
  {
    id: '5',
    itemId: 'minecraft:oak_planks',
    name: 'Oak Planks',
    stackable: true,
    size: 64,
    url: 'https://minecraftitemids.com/item/128/oak_planks.png',
  },
  {
    id: '6',
    itemId: 'minecraft:oak_sapling',
    name: 'Oak Sapling',
    stackable: true,
    size: 64,
    url: 'https://minecraftitemids.com/item/128/oak_sapling.png',
  },
  {
    id: '7',
    itemId: 'minecraft:bedrock',
    name: 'Bedrock',
    stackable: true,
    size: 64,
    url: 'https://minecraftitemids.com/item/128/bedrock.png',
  },
];

module.exports = { blocks };
